# See AppVeyor.yml reference:
# https://www.appveyor.com/docs/appveyor-yml/

version: 2018.1.{build}-{branch}

only_commits:
  author: richard.goulter@gmail.com

image:
  - Visual Studio 2017

platform:
  - x64

configuration: Release

# Need to cache the installed vcpkgs
cache:
  - c:\tools\vcpkg\installed\

init:
  - cmd: c:/tools/vcpkg/vcpkg.exe install opencv:x64-windows
  - cmd: c:/tools/vcpkg/vcpkg.exe install qt5:x64-windows

before_build:
  - cmd: cmake -H%APPVEYOR_BUILD_FOLDER% -B%APPVEYOR_BUILD_FOLDER%\build -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake

after_build:
  - cmd: cmake --build %APPVEYOR_BUILD_FOLDER%\build --config %CONFIGURATION%

artifacts:
  - path: $(APPVEYOR_BUILD_FOLDER)\build