# See AppVeyor.yml reference:
# https://www.appveyor.com/docs/appveyor-yml/

version: 2018.1.{build}-{branch}

only_commits:
  author: richard.goulter@gmail.com

image:
  - Visual Studio 2017

platform:
  - x64

configuration: Release

# Need to cache the installed vcpkgs
# (Caching doesn't affect init, so must use vcpkg in before_build)
cache:
  - c:\Tools\vcpkg\installed\

before_build:
  - cmd: c:/tools/vcpkg/vcpkg.exe install opencv:x64-windows
  - cmd: set VCPKG_TOOLCHAIN=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake
  - cmd: set Qt5_DIR=C:\Qt\5.10.0\msvc2017_64
  - cmd: set Qt5Widgets_DIR=%Qt5_DIR%\lib\cmake\Qt5Widgets
  - cmd: cmake -DVCPKG_TARGET_TRIPLET=x64-windows -H%APPVEYOR_BUILD_FOLDER% -B%APPVEYOR_BUILD_FOLDER%/build -DCMAKE_TOOLCHAIN_FILE=%VCPKG_TOOLCHAIN%

after_build:
  - cmd: cmake --build %APPVEYOR_BUILD_FOLDER%\build --config %CONFIGURATION%

artifacts:
  - path: $(APPVEYOR_BUILD_FOLDER)\build
