language: c++

matrix:
 include:
   - os: linux
     dist: trusty
     sudo: required
#    - os: osx

compiler:
  - gcc

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get -qq update;
      sudo apt-get install -y libopencv-dev qt5-default libqt5opengl5-dev;
    fi
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
#      brew update
#      /usr/bin/yes | pip2 uninstall numpy;
#      brew install opencv;
#      brew install qt5;
#      export CMAKE_PREFIX_PATH=$(brew --prefix qt5);
#    fi

script:
  - mkdir build
  - cd build
  - cmake -Dtest=ON ..
  - make
  - ./runUnitTests
